services:
    alex_dpy_simple_acl.acl:
        class: AlexDpy\Acl\Acl
        arguments:
            - @alex_dpy_simple_acl.database_provider
            - @alex_dpy_simple_acl.permission_buffer
            - %alex_dpy_simple_acl.mask_builder_class%

    alex_dpy_simple_acl.permission_buffer:
        class: AlexDpy\Acl\Cache\PermissionBuffer
